### ISSUE TITLE
Lab 05 Public Label missing

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/10993-IntegratingOn-PremisesIdentitywithAzure#1]
Lab 05 AK, Exercise 3, Task 2, Step #8:

> 8.  Click  **Public** in the **Microsoft Azure Information Protection** window, and then click **OK**. Save the document.

There is no **Public** label--was this a default that has now changed, or are the instructions for creating it missing?

**Comment by ddamir76** [comment]
Public label should be there by default. Please double check this. This label is created by default once the AIP is activated.
