### ISSUE TITLE
Mod 4 Lab, Exercise 3 - MFA Server replaced with NPS Extension

### ISSUE THREAD

**Issue by itbland** [MicrosoftLearning/10993-IntegratingOn-PremisesIdentitywithAzure#3]
https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-mfa-nps-extension

https://www.microsoft.com/en-us/download/details.aspx?id=54688

MFA Server link is no longer available in the Azure Portal.

> As of July 1, 2019, Microsoft will no longer offer MFA Server for new deployments. New customers who would like to require multi-factor authentication from their users should use cloud-based Azure Multi-Factor Authentication. Existing customers who have activated MFA Server prior to July 1 will be able to download the latest version, future updates and generate activation credentials as usual.
https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-mfaserver-deploy

**Comment by ddamir76** [comment]
fixed and closed
